version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    machine:
        environment:
          _JAVA_OPTIONS: "-Xmx3200m"
        node:
          version: 8.1.2
    steps:
      - checkout
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
          command: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
      - run:
          command: echo y | android update sdk -u -a -t tools
      - run:
          command: echo y | android update sdk -u -a -t platform-tools
      - run:
          command: echo y | android update sdk -u -a -t build-tools-25.0.2
      - run:
          command: echo y | android update sdk -u -a -t android-25
      - run:
          command: echo y | android update sdk -u -a -t extra-google-m2repository
      - run:
          command: echo y | node --version
      - run:
          command: echo y | npm --version
      - run:
          command: echo y | npm install -g appium
      - run:
          command: echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
      - run:
          command: echo y | adb devices
      - run:
          name: Run Tests
          command: ./gradlew clean build uiAutomationTest -x test -x signArchives
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

