version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-node8-alpha

    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew

      - run:
          command: echo y | android update sdk -u -a -t tools
      - run:
          command: echo y | android update sdk -u -a -t platform-tools
      - run:
          command: echo y | android update sdk -u -a -t build-tools-25.0.2
      - run:
          command: echo y | android update sdk -u -a -t android-25

      - run:
          command: echo y | android update sdk -u -a -t sys-img-armeabi-v7a-android-25
      - run:
          command:   echo y | android update sdk -u -a -t addon-google_apis-google-25
      - run:
          command:   echo y | android update sdk -u -a -t extra-android-m2repository
      - run:
          command:   echo y | android update sdk -u -a -t extra-google-google_play_services
      - run:
          command:   echo y | android update sdk -u -a -t extra-google-m2repository
      - run:
          command: echo y | android update sdk -u -a -t extra-google-m2repository
      - run:
          command: echo y | node --version
      - run:
          command: echo y | npm --version
      - run:
          command: sudo npm i -g appium --unsafe-perm=true --allow-root
      - run:
          name: List available targets and other sdk modules
          command: sdkmanager --list --include_obsolete --verbose
      - run:
          command: echo no | avdmanager create avd -n test -k "system-images;android-25;default;armeabi-v7a"
      - run:
          command: /opt/android-sdk-linux/emulator/emulator -avd testEmulator -no-audio -no-window


      - run:
          command: adb devices

      - run:
          command: echo y | adb devices
      - run:
          name: Run Tests
          command: ./gradlew clean build uiAutomationTest -x test -x signArchives
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

